apiVersion: v1
kind: Service
metadata:
  name: samplehtml-svc
spec:
  selector:
    app: samplehtml
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer


  kubectl
          mkdir .kube
          touch .kube/config
          echo ${{ secrets.KUBE_CONFIG }} > .kube/config